[package]
name = "i3status"
description = "i3status but for myself"
version = "0.1.0"
authors = ["LightDiscord <arnaud@lightdiscord.me>"]
repository = "https://github.com/LightDiscord/myStatus"
license = "MIT"

[dependencies]
futures = "0.2.1"
tokio = "0.1.7"
error-chain = "0.11.0"
